name: Tests
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "0 13 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (${{ matrix.python-version }} | ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Create conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          micromamba-version: 'latest'
          environment-file: requirments.txt
          extra-specs: |
            python=${{ matrix.python-version }}
      - name: Install gcm-filters
        shell: bash -l {0}
        run: |
          python -m pip install -e . --no-deps --force-reinstall
      - name: Run Tests
        shell: bash -l {0}
        run: |
          pytest --cov=./ --cov-report=xml
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
